name: Build and upload CLI executables

on:
    release:
        types: [published]

permissions:
    contents: write

jobs:
    build_and_upload_assets:
        name: Build & upload CLI for ${{ github.event.release.tag_name }}
        strategy:
            fail-fast: false
            matrix:
                config:
                    - os: ubuntu-latest
                      target: bun-linux-x64
                      asset_name_suffix: linux-x64
                      output_filename_override: ""
                      keyring_import: "linux-x64-gnu"
                    - os: ubuntu-latest
                      target: bun-linux-arm64
                      asset_name_suffix: linux-arm64
                      output_filename_override: ""
                      keyring_import: "linux-arm64-gnu"
                    - os: ubuntu-latest
                      target: bun-darwin-x64
                      asset_name_suffix: darwin-x64
                      output_filename_override: ""
                      keyring_import: "darwin-x64"
                    - os: ubuntu-latest
                      target: bun-darwin-arm64
                      asset_name_suffix: darwin-arm64
                      output_filename_override: ""
                      keyring_import: "darwin-arm64"
                    - os: ubuntu-latest
                      target: bun-windows-x64
                      asset_name_suffix: windows-x64
                      output_filename_override: ".exe"
                      keyring_import: "win32-x64-msvc"
        runs-on: ${{ matrix.config.os }}
        steps:
            - name: Checkout code for release tag
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.release.tag_name }}

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: Require keyring import
              run: |
                  cd apps/cli/src
                  wget https://github.com/Brooooooklyn/keyring-node/releases/latest/download/keyring.${{ matrix.config.keyring_import }}.node
                  SEARCH_STRING="// <ci-keyring-import>"
                  REPLACE_STRING="require(\"./keyring.${{ matrix.config.keyring_import }}.node\");"
                  sed -i "s|$SEARCH_STRING|$REPLACE_STRING|g" src/index.ts

            - name: Compile CLI
              run: |
                  OUT_FILENAME="livecomp-${{ matrix.config.asset_name_suffix }}${{ matrix.config.output_filename_override }}"
                  echo "Building: $OUT_FILENAME for target ${{ matrix.config.target }}"

                  cd apps/cli && bun build ./src/index.ts \
                    --compile \
                    --minify \
                    --sourcemap \
                    --bytecode \
                    --outfile ./dist/$OUT_FILENAME \
                    --target ${{ matrix.config.target }} \

            - name: Upload release asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ github.event.release.upload_url }}
                  asset_path: apps/cli/dist/livecomp-${{ matrix.config.asset_name_suffix }}${{ matrix.config.output_filename_override }}
                  asset_name: livecomp-${{ matrix.config.asset_name_suffix }}${{ matrix.config.output_filename_override }}
                  asset_content_type: application/octet-stream

