name: Lint & Format

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

permissions:
    checks: write
    contents: write

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2

            - name: Install dependencies
              run: bun install --frozen-dependencies

            - name: Lint client
              run: cd apps/client && bunx eslint --fix "src/**/*.{ts,tsx}"

            - name: Lint server
              run: cd apps/server && bunx eslint --fix "src/**/*.{ts,tsx}"

            - name: Lint CLI
              run: cd apps/cli && bunx eslint --fix "src/**/*.{ts,tsx}"

            - name: Lint shared
              run: cd packages/shared && bunx eslint --fix "src/**/*.{ts,tsx}"

            - name: Lint utils
              run: cd packages/utils && bunx eslint --fix "src/**/*.{ts,tsx}"

            - name: Format
              run: bunx prettier --write .

