name: Typecheck

on:
    push:
        branches:
            - main
    pull_request:

permissions:
    checks: write
    contents: write

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2

            - name: Install dependencies
              run: bun install --frozen-dependencies

            - name: Typecheck client
              run: cd packages/client && bunx tsc --noEmit

            - name: Typecheck server
              run: cd packages/server && bunx tsc --noEmit

            - name: Typecheck utils
              run: cd packages/utils && bunx tsc --noEmit

